baseURL = "https://nelson1995.github.io"
languageCode = "en-us"
title = "Nelson1995"
theme="archie"
copyright = "© Nelson Guest Katale · Powered by [Hugo](https://gohugo.io/) & [Archie](https://github.com/athul/archie)"
# Code Highlight
pygmentsstyle = "monokai"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true

disqusShortname = "yourDisqusShortname"
assetDir = "static"
paginate=5 # articles per page
publishDir = "docs"

[params]
	mode="dark" # color-mode → light,dark,toggle or auto
	useCDN=false # don't use CDNs for fonts and icons, instead serve them locally.
	#subtitle = "Minimal and Clean [blog theme for Hugo](https://github.com/athul/archie)"
	subtitle = "Welcome to my space."
	islatestposts = true
	mathjax = true # enable MathJax support
	katex = true # enable KaTeX support

	search = "/search"
	allposts = "/posts"
	linkedIn = "https://linkedin.com/in/nelson-guest-katale"
    placeholder = "Type here to search..."
    custom_search = ["css/search.css"]

[outputs]
    home = [ "HTML", "RSS", "JSON"]
    page = ["HTML", "RSS"]

# Social Tags

[[params.social]]
name = "GitHub"
icon = "github"
url = "https://github.com/nelson1995/nelson-portfolio-site/"

[[params.social]]
name = "LinkedIn"
icon = "linkedin"
url = "https://linkedin.com/in/nelson-guest-katale"

[[params.social]]
name = "StackOverflow"
icon = "link"
url = "https://stackoverflow.com/users/7519779/nelson-katale"

# Main menu Items

[[menu.main]]
name = "Home"
url = "/"
weight = 1

[[menu.main]]
name = "All posts"
url = "/posts"
weight = 2

[[menu.main]]
name = "Projects"
url = "/projects"
weight = 3

[[menu.main]]
name = "About"
url = "/me"
weight = 4

[[menu.main]]
name = "Tags"
url = "/tags"
weight = 5

[[menu.main]]
name = "Search"
url = "/search"
weight = 6
